// Generated by CoffeeScript 1.5.0
(function() {

  angular.module('noughts').controller('GameCtrl', function($scope, Board, Bot) {
    var botTurn,
      _this = this;
    $scope.board = this.board = new Board();
    this.bot = new Bot(this.board);
    $scope.mark = function(index, player) {
      var marked;
      marked = _this.board.mark(index, _this.board.HUMAN);
      if (marked) {
        return botTurn();
      }
    };
    return botTurn = function() {
      return _this.board.mark(_this.bot.nextMove(), _this.board.BOT);
    };
  });

}).call(this);
